/**
 * END-TO-END TEST GLUE. This file is hand-written and is NOT generated by djng or ngdj.
 *
 * The generated `customers` table leaves its columns and rows to the host, and nothing
 * binds it to a generated API client, so the end-to-end flow supplies this small host.
 * It loads the page the table requests (`?page=N`) through the generated
 * `CustomersDataService`, which wraps the `CustomersApiService` that ng-openapi-gen
 * generated, and feeds the rows and the total to the table. A failed request goes
 * through the generated `ResourceAdapter`, which only logs it, so the error state shown
 * here is the glue's own.
 *
 * The "Add customer" button writes through the generated `CustomersApiService` too, so the
 * end-to-end flow can check that the generated transport sends Django's CSRF token with a
 * signed-in write. The glue shows its own error when the write is refused.
 *
 * The run replaces the two placeholder import paths below with the paths of the generated
 * data service and of the ng-openapi-gen output directory.
 */
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { from, Observable } from 'rxjs';

import type { Customer } from '__GENERATED_API__/models/customer';
import { CustomersDataService } from '__DATA_SERVICE__';
import {
  ResourceAdapter,
  type PaginatedResult,
  type ResourceQuery,
} from '../../api-integration/resource-adapter';
import {
  CustomersTableComponent,
  type CustomersTableColumn,
  type CustomersTablePage,
} from '../../shared/tables/customers-table/customers-table';

/**
 * The customers list of the generated data service, behind the generated adapter contract.
 * The generated service methods return a Promise, the data service takes an Observable.
 */
class CustomersListAdapter extends ResourceAdapter<Customer> {
  private readonly data = inject(CustomersDataService);

  list(query: ResourceQuery = {}): Observable<PaginatedResult<Customer>> {
    return this.adapt(
      this.data.list(() =>
        from(this.data.apiService.customersList$Response({ page: query.page })),
      ),
      'customers list',
    ) as Observable<PaginatedResult<Customer>>;
  }

  retrieve(): Observable<Customer> {
    throw new Error('Not used by the end-to-end flow.');
  }

  create(): Observable<Customer> {
    throw new Error('Not used by the end-to-end flow.');
  }

  update(): Observable<Customer> {
    throw new Error('Not used by the end-to-end flow.');
  }

  delete(): Observable<void> {
    throw new Error('Not used by the end-to-end flow.');
  }
}

@Component({
  selector: 'app-customers-host',
  standalone: true,
  imports: [CustomersTableComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (failed()) {
      <p role="alert" data-testid="customers-error">Customers could not be loaded.</p>
    }
    <button type="button" data-testid="create-customer" (click)="createCustomer()">
      Add customer
    </button>
    @if (writeError(); as message) {
      <p role="alert" data-testid="customers-write-error">{{ message }}</p>
    }
    <app-customers-table
      caption="Customers"
      [columns]="columns"
      [rows]="rows()"
      [totalRows]="count()"
      [pageIndex]="pageIndex()"
      [pageSize]="pageSize"
      [pageSizeOptions]="pageSizeOptions"
      (paginated)="paginateCustomers($event)"
    />
  `,
})
export class CustomersHostComponent {
  protected readonly columns: readonly CustomersTableColumn<Customer>[] = [
    { key: 'id', label: 'Id' },
    { key: 'name', label: 'Name' },
    { key: 'email', label: 'Email' },
    { key: 'phone', label: 'Phone' },
    { key: 'active', label: 'Active' },
  ];
  // The tutorial API uses PageNumberPagination with a fixed page size of 10.
  protected readonly pageSize = 10;
  protected readonly pageSizeOptions = [10];

  protected readonly rows = signal<readonly Customer[]>([]);
  protected readonly count = signal(0);
  protected readonly pageIndex = signal(0);
  protected readonly failed = signal(false);
  protected readonly writeError = signal<string | null>(null);

  private readonly adapter = new CustomersListAdapter();
  private readonly data = inject(CustomersDataService);

  constructor() {
    this.load(0);
  }

  /** The handler the OpenUI document binds: `paginateCustomers($event)`. */
  protected paginateCustomers(page: CustomersTablePage): void {
    this.load(page.pageIndex);
  }

  /** Creates a customer through the generated service; the transport adds the CSRF token. */
  protected async createCustomer(): Promise<void> {
    this.writeError.set(null);
    const body = {
      name: 'E2E Written Customer',
      email: 'e2e.written@example.com',
      phone: '+1-555-0199',
      active: true,
    } as Customer;
    try {
      await this.data.apiService.customersCreate$Json({ body });
      this.load(this.pageIndex());
    } catch (error) {
      const status = (error as { status?: number }).status ?? 'unknown';
      this.writeError.set(`The customer could not be created (HTTP ${status}).`);
    }
  }

  private load(pageIndex: number): void {
    this.adapter.list({ page: pageIndex + 1 }).subscribe({
      next: (response) => {
        this.rows.set(response.results);
        this.count.set(response.count);
        this.pageIndex.set(pageIndex);
        this.failed.set(false);
      },
      error: () => {
        this.rows.set([]);
        this.count.set(0);
        this.failed.set(true);
      },
    });
  }
}
